language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
os:
  - linux
  - osx
install: 
  - "pip install nose"
  - "pip install coverage"
  - "pip install codecov"
script: nosetests --with-coverage
after_success:
    codecov
